## Installation of the CloudNativePG operator - see https://cloudnative-pg.io/documentation/
cnpg:
  # -- should the CloudNativePG operator be installed
  enabled: true

## Usage of the CloudNativePG operator - see https://cloudnative-pg.io/documentation/
managedPostgres:
  # -- should it be enabled? Requires the CloudNativePG CRDs to be installed before applying the chart
  enabled: true
  # -- config as defined in https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/
  config:
    instances: 1
    imageName: ghcr.io/cloudnative-pg/postgresql:16.9
    storage:
      size: 1Gi
    enableSuperuserAccess: true
    bootstrap:
      initdb:
        database: tildb
        owner: postgres

# -- configuration for the trusted-issuers-list to be deployed as part of the trust-anchor, see https://github.com/FIWARE/helm-charts/tree/main/charts/trusted-issuers-list for all options
trusted-issuers-list:
  # -- should it be enabled? set to false if one outside the chart is used.
  enabled: true
  # -- allows to set a fixed name for the services
  fullnameOverride: tir
  # -- connection to the database
  database:
    # -- should persistence be used?
    persistence: true
    # -- name of the db dialect
    dialect: POSTGRES
    # -- name of the db user
    username: postgres
    # -- configuration for the existing secret to get the passwords from
    existingSecret:
      enabled: true
      name: postgres-superuser
      key: password
    # -- host of the database
    host: postgres-rw
    # -- host of the database
    port: 5432
    # -- name of the schema inside the db
    name: tildb
